name: CI/CD Pipeline for Dev Branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test-lint-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Cache Python Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m venv .venv
        echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8  # Removed hadolint from pip install

    - name: Install Hadolint
      run: |
        wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        chmod +x /usr/local/bin/hadolint

    - name: Run Unit Tests
      run: |
        $VIRTUAL_ENV/bin/pytest test_app.py

    - name: Lint Python Code
      run: |
        $VIRTUAL_ENV/bin/flake8 app.py test_app.py --max-line-length=88

    - name: Lint Dockerfile
      run: |
        hadolint Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t zainab273/flask-math-api:dev .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push zainab273/flask-math-api:dev

    - name: Security Scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'zainab273/flask-math-api:dev'
        format: 'table'
